name: flutter_google_places
description: Google places autocomplete widgets for flutter. No wrapper, use
  https://pub.dev/packages/google_maps_webservice
version: 0.4.0
repository: https://github.com/fluttercommunity/flutter_google_places

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_api_headers: 4.0.3
  google_maps_webservice: ^0.0.19
  http: ^0.13.6
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  assets:
    - packages/flutter_google_places/assets/google_black.png
    - packages/flutter_google_places/assets/google_white.png
